{% set version = "5.0.1" %}

# handle undefined PYTHON in `noarch: generic` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: pypdf
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pypdf/pypdf-{{ version }}.tar.gz
    sha256: a361c3c372b4a659f9c8dd438d5ce29a753c79c620dc6e1fd66977651f5547ea
  - folder: src
    url: https://github.com/py-pdf/pypdf/archive/refs/tags/{{ version }}.tar.gz
    sha256: 7253a816090c0f461d20f6465d26624ca4a4a4d8b4f3c4fc9ca7a804fb744352

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - flit-core >=3.9,<4
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - typing_extensions >=4.0

test:
  imports:
    - pypdf
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: pypdf

  - name: pypdf-with-crypto
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("pypdf", max_pin="x.x.x") }}
        - cryptography
    test:
      imports:
        - pypdf
      commands:
        - pip check
      requires:
        - pip


  - name: pypdf-with-image
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("pypdf", max_pin="x.x.x") }}
        - pillow >=8.0.0
    test:
      imports:
        - pypdf
      commands:
        - pip check
      requires:
        - pip


  - name: pypdf-with-full
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("pypdf-with-crypto", max_pin="x.x.x") }}
        - {{ pin_subpackage("pypdf-with-image", max_pin="x.x.x") }}
        - {{ pin_subpackage("pypdf", max_pin="x.x.x") }}
      test:
        imports:
          - pypdf
        commands:
          - pip check
        requires:
          - pip

  - name: _pypdf-with-full-tests
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("pypdf-with-crypto", max_pin="x.x.x") }}
        - {{ pin_subpackage("pypdf-with-full", max_pin="x.x.x") }}
        - {{ pin_subpackage("pypdf-with-image", max_pin="x.x.x") }}
        - {{ pin_subpackage("pypdf", max_pin="x.x.x") }}
    test:
      files:
        - test_all.py
      source_files:
        - src/pyproject.toml
        - src/tests
        - src/resources
      imports:
        - pypdf
      commands:
        - pip check
        - python test_all.py
      requires:
        - fpdf
        - pip
        - pytest-cov
        - pytest-socket
        - pytest-timeout
        - pyyaml
        - types-pillow

about:
  home: https://pypi.org/project/pypdf
  summary: A pure-python PDF library capable of splitting, merging, cropping, and transforming PDF files
  license: BSD-3-Clause
  license_file: dist/LICENSE
  dev_url: https://github.com/py-pdf/pypdf
  doc_url: https://pypdf.readthedocs.io

extra:
  feedstock-name: pypdf
  recipe-maintainers:
    - MartinThoma
    - bollwyvl
