{% set version = "4.3.1" %}

# handle undefined PYTHON in `noarch: generic` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: pypdf-split
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pypdf/pypdf-{{ version }}.tar.gz
    sha256: b2f37fe9a3030aa97ca86067a56ba3f9d3565f9a791b305c7355d8392c30d91b
  - folder: src
    url: https://github.com/py-pdf/pypdf/archive/refs/tags/{{ version }}.tar.gz
    sha256: c7d6c9ddb6587ffd13ed3678d74842decf2aa209cba97c661830296c0e2c33bd

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
  run:
    - python >=3.7

outputs:

  - name: pypdf
    build:
      script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      noarch: python
    requirements:
      host:
        - flit-core >=3.9,<4
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - typing_extensions >=4.0
    test: &simple-test
      imports:
        - pypdf
      commands:
        - pip check
      requires:
        - pip

  - name: pypdf-with-crypto
    build: &noarch-generic
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("pypdf", exact=True) }}
        - cryptography
    test: *simple-test

  - name: pypdf-with-image
    build: *noarch-generic
    requirements:
      run:
        - {{ pin_subpackage("pypdf", exact=True) }}
        - pillow >=8.0.0
    test: *simple-test

  - name: pypdf-with-full
    build: *noarch-generic
    requirements:
      run:
        - {{ pin_subpackage("pypdf-with-crypto", exact=True) }}
        - {{ pin_subpackage("pypdf-with-image", exact=True) }}
        - {{ pin_subpackage("pypdf", exact=True) }}
    test: *simple-test

  - name: _pypdf-with-full-tests
    build: *noarch-generic
    requirements:
      run:
        - {{ pin_subpackage("pypdf-with-crypto", exact=True) }}
        - {{ pin_subpackage("pypdf-with-full", exact=True) }}
        - {{ pin_subpackage("pypdf-with-image", exact=True) }}
        - {{ pin_subpackage("pypdf", exact=True) }}
    test:
      files:
        - test_all.py
      source_files:
        - src/pyproject.toml
        - src/tests
        - src/resources
      imports:
        - pypdf
      commands:
        - pip check
        - python test_all.py
      requires:
        - fpdf
        - pip
        - pytest-cov
        - pytest-socket
        - pytest-timeout
        - pyyaml
        - types-pillow

about:
  home: https://pypi.org/project/pypdf
  summary: A pure-python PDF library capable of splitting, merging, cropping, and transforming PDF files
  license: BSD-3-Clause
  license_file: dist/LICENSE
  dev_url: https://github.com/py-pdf/pypdf
  doc_url: https://pypdf.readthedocs.io

extra:
  feedstock-name: pypdf
  recipe-maintainers:
    - MartinThoma
    - bollwyvl
