# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "5.3.1"
  PYTHON: ${{ PYTHON | default("$PYTHON") }}

recipe:
  name: pypdf
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/pypdf/pypdf-${{ version }}.tar.gz
    sha256: 0b9b715252b3c60bacc052e6a780e8b742cee9b9a2135f6007bb018e22a5adad
    target_directory: dist
  - url: https://github.com/py-pdf/pypdf/archive/refs/tags/${{ version }}.tar.gz
    sha256: 1c6089ad527376dbe362db25528ec9951843b42394de6830149cae6bd515a5bf
    target_directory: src

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: pypdf
    build:
      noarch: python
      script:
        - cd dist
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - flit-core >=3.9,<4
        - pip
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - typing_extensions >=4.0
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports: pypdf

  - package:
      name: pypdf-with-crypto
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("pypdf", upper_bound="x.x.x") }}
        - cryptography
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports: pypdf

  - package:
      name: pypdf-with-image
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("pypdf", upper_bound="x.x.x") }}
        - pillow >=8.0.0
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports: pypdf

  - package:
      name: pypdf-with-full
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("pypdf-with-crypto", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("pypdf-with-image", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("pypdf", upper_bound="x.x.x") }}
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports: pypdf

  - package:
      name: _pypdf-with-full-tests
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("pypdf-with-crypto", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("pypdf-with-full", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("pypdf-with-image", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("pypdf", upper_bound="x.x.x") }}
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}.*
          imports: pypdf
      - files:
          recipe:
            - test_all.py
          source:
            - src/pyproject.toml
            - src/tests/
            - src/resources/
        requirements:
          run:
            - fpdf
            - pytest-cov
            - pytest-socket
            - pytest-timeout
            - pyyaml
            - types-pillow
            - python ${{ python_min }}.*
        script:
          - python test_all.py

about:
  summary: A pure-python PDF library capable of splitting, merging, cropping, and transforming PDF files
  license: BSD-3-Clause
  license_file: dist/LICENSE
  homepage: https://pypi.org/project/pypdf
  repository: https://github.com/py-pdf/pypdf
  documentation: https://pypdf.readthedocs.io

extra:
  feedstock-name: pypdf
  recipe-maintainers:
    - MartinThoma
    - bollwyvl
